### ISSUE TITLE
[Bug]: Issue with login 

### ISSUE THREAD

**Issue by ank1traj** [WebSorcery/cucoders#10]
### What happened?

A bug happened! Even after login if we change the page get logout.

### Version

1.0.0 (Default)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What OS are you seeing the problem on?

Windows, MacOS, Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by singhcoder694** [comment]
Your last method of authentication was working properly I guess, then why to switch of Auth0 . This is the main reason why error is there....

**Comment by ank1traj** [comment]
I am looking to move out for clerk instead of auth0. We moved to auth0 due to user management and other features too.

**Comment by singhcoder694** [comment]
Also is it problem with my setup only or with everyone's, it takes alot of time to upadate my codes locally on website. I need to w8 for more time to see the changes.

**Comment by ank1traj** [comment]
I don't think so because it's working fine for me.

**Comment by singhcoder694** [comment]
Due to auth0 it is not possible to check locally if issue is fixed or not for that I need to make my own Auth id and key.... In this case should we do it by making our own?

**Comment by ank1traj** [comment]
Yeah for sure

**Comment by singhcoder694** [comment]
In auth0 panel check for this that links are set properly in all three specified below, it may be reason of logout if not set properly...

<img width="754" alt="Screenshot 2023-12-14 111914" src="https://github.com/WebSorcery/cucoders/assets/114601400/fcbd8709-bc29-4663-9b9f-ae13fbda55ad">
<img width="427" alt="Screenshot 2023-12-14 111929" src="https://github.com/WebSorcery/cucoders/assets/114601400/dff115a4-6b89-470b-804f-d3887b428357">

**Comment by ank1traj** [comment]
All are updated as expected
