### ISSUE TITLE
[Bug]: Fixing Links in our partners section for github and codechef

### ISSUE THREAD

**Issue by YashSachan2** [WebSorcery/cucoders#7]
### Contact Details

yash.sachan.ece22@itbhu.ac.in

### What happened?

A bug happened! The github link is not working due to wrong url (instead of wwww it should be www) and for the codechef case it redirects to linkedin page of Dot Question Mark

### Version

1.0.0 (Default)

### What browsers are you seeing the problem on?

Chrome

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YashSachan2** [comment]
@ank1traj I have made the pr
Please look into it

**Comment by ank1traj** [comment]
Merged the PR. Points given for this.
